platform :ios, '9.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target "yunbaolive" do
#图片
pod 'SDWebImage','5.2.5'
#网络请求
pod 'MJRefresh','3.2.0'
pod 'AFNetworking','4.0.1'


pod 'ZFPlayer'
pod 'ZFPlayer/ControlView'
pod 'ZFPlayer/ijkplayer', '3.3.3'

#极光
pod 'JPush','3.3.4'
pod 'JMessage','3.9.1'
#极光日志打印
pod 'CocoaLumberjack','3.4.2'
#bugly
pod 'Bugly', '2.4.7'
#支付宝
pod 'AliPay','15.7.4.2'
pod 'OpenSSL-for-iOS', '1.0.2.d.1'
#UI
pod 'Masonry', '1.0.2'
#分享
pod 'mob_sharesdk','4.3.16' 
pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
#pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'   #（微信sdk不带支付的命令）
pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' #（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个）
pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'
pod 'mob_sharesdk/ShareSDKPlatforms/Apple' #苹果登录

#SVGAPlayer
pod 'SVGAPlayer','2.3.5'
#弹窗
pod 'CWStatusBarNotification', '2.3.5'
#金山SDK
pod 'libksygpulive', :git => 'https://github.com/ksvc/KSYLive_iOS.git', :tag => 'v3.0.5'
#七牛
pod 'Qiniu','7.4.3'
#腾讯SDK
#pod 'TXLiteAVSDK_UGC', '3.9.2749'
pod 'TXLiteAVSDK_Professional','7.7.9458'
#腾讯上传
pod 'QCloudCOSXML','5.7.4'

#AT 功能
pod 'HPGrowingTextView','1.1'
#YYImage用来加载gif
pod 'YYWebImage','1.0.5'
pod 'YYText','1.0.7'

#友盟统计
pod 'UMCCommon','2.1.1'
pod 'UMCAnalytics','5.5.2'
#pod 'UMCSecurityPlugins'
#  轮播图
pod 'SDCycleScrollView','1.82'
#动画
pod 'lottie-ios', '2.5.3'

use_frameworks!
#socket.io
pod 'Socket.IO-Client-Swift','15.1.0'
pod 'MBProgressHUD','1.1.0'
pod 'EBBannerView','1.0.8'
#图片选择器
pod 'TZImagePickerController', '~> 3.5.2'
pod 'SPPageMenu', '3.5.0'
#AWS
pod 'AWSS3','2.19.1'
#Braintree
pod 'BraintreeDropIn', "8.1.2"
pod 'CodeInstallSDK', "1.3.1"
end
